apiVersion: v2
name: kubero
description: A self-hosted PaaS platform for deploying applications on Kubernetes without specialized knowledge
type: application
version: 0.1.0
appVersion: "3.1.1"
keywords:
  - kubero
  - paas
  - platform
  - deployment
  - gitops
  - heroku
  - developer-platform
  - ci-cd
  - kubernetes
home: https://www.kubero.dev
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/kubero
  - https://github.com/kubero-dev/kubero
  - https://github.com/kubero-dev/kubero-operator
maintainers:
  - name: CloudPirates GmbH & Co. KG
    email: hello@cloudpirates.io
    url: https://www.cloudpirates.io
dependencies:
  - name: common
    version: "2.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
icon: https://raw.githubusercontent.com/kubero-dev/docs/refs/heads/main/static/assets/logo/kubero-logo-horizontal.png
annotations:
  license: GPL-3.0
  artifacthub.io/category: integration-delivery
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/signKey: |
    fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
    url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
  artifacthub.io/links: |
    - name: Kubero
      url: https://www.kubero.dev
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/kubero
    - name: Kubero Main Repository
      url: https://github.com/kubero-dev/kubero
    - name: Kubero Operator
      url: https://github.com/kubero-dev/kubero-operator
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/changes: |2
        - kind: added
          description: "Initial Kubero Helm chart for deploying operator and UI"
          links:
            - name: "Feature Request"
              url: "https://github.com/CloudPirates-io/helm-charts/issues"