{{- if .Values.operator.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubero.operator.fullname" . }}
  namespace: {{ include "cloudpirates.namespace" . | quote }}
  labels:
    {{- include "kubero.operator.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubero.operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubero.operator.selectorLabels" . | nindent 8 }}
        {{- with .Values.operator.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with (mergeOverwrite (deepCopy .Values.commonAnnotations) .Values.operator.podAnnotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "kubero.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "kubero.serviceAccountName" . }}
      {{- with .Values.operator.podSecurityContext }}
      {{- if .enabled }}
      securityContext:
        {{- toYaml (omit . "enabled") | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: operator
          image: {{ include "kubero.operator.image" . }}
          imagePullPolicy: {{ .Values.operator.image.imagePullPolicy }}
          {{- with .Values.operator.containerSecurityContext }}
          {{- if .enabled }}
          securityContext:
            {{- toYaml (omit . "enabled") | nindent 12 }}
          {{- end }}
          {{- end }}
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubero-operator"
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          {{- if .Values.operator.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml (omit .Values.operator.livenessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.operator.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml (omit .Values.operator.readinessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- with .Values.operator.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}