{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubero.fullname" . }}-operator
  labels:
    {{- include "kubero.operator.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  # Allow operator to manage Custom Resources
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Allow operator to manage Kubero resources
  - apiGroups:
      - application.kubero.dev
    resources:
      - kuberos
      - kuberoapps
      - kuberopipelines
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - application.kubero.dev
    resources:
      - kuberos/finalizers
      - kuberoapps/finalizers
      - kuberopipelines/finalizers
    verbs:
      - update
  - apiGroups:
      - application.kubero.dev
    resources:
      - kuberos/status
      - kuberoapps/status
      - kuberopipelines/status
    verbs:
      - get
      - patch
      - update
  # Allow operator to manage core Kubernetes resources
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - services
      - serviceaccounts
      - persistentvolumeclaims
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Allow operator to manage deployments
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Allow operator to manage ingress
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Allow operator to manage RBAC
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Allow operator to read nodes and namespaces
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubero.fullname" . }}-operator
  labels:
    {{- include "kubero.operator.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubero.fullname" . }}-operator
subjects:
  - kind: ServiceAccount
    name: {{ include "kubero.serviceAccountName" . }}
    namespace: {{ include "cloudpirates.namespace" . | quote }}
{{- end }}