apiVersion: v2
name: etcd
description: etcd is a distributed reliable key-value store for the most critical data of a distributed system
type: application
version: 0.2.0
appVersion: "3.6.5"
keywords:
  - etcd
  - distributed
  - key-value
  - consensus
  - raft
home: https://etcd.io/
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/mariadb
  - https://github.com/etcd-io/etcd
maintainers:
  - name: CloudPirates GmbH & Co. KG
    email: hello@cloudpirates.io
    url: https://www.cloudpirates.io
dependencies:
  - name: common
    version: "2.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
icon: https://a.storyblok.com/f/143071/513x513/36b7a72378/etcd-logo.svg
annotations:
  license: Apache-2.0
  artifacthub.io/category: database
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/signKey: |
    fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
    url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
  artifacthub.io/links: |
    - name: etcd
      url: https://etcd.io/
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/mariadb
    - name: Application
      url: https://github.com/etcd-io/etcd
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/changes: |2
        - kind: added
          description: "Initial chart release"
